<section class="footer__copy" id="dynamic-select">
<div class="row">
<ul>
<li><a href="https://www.konicaminolta.jp/siteinfo/terms.html" target="_blank">サイトのご利用について</a></li><li><a href="https://www.konicaminolta.jp/siteinfo/privacypolicy.html" target="_blank">個人情報保護方針</a></li><li><a href="https://www.konicaminolta.jp/siteinfo/sitemap.html" target="_blank">サイトマップ</a></li>
</ul>
<small>©2011-<script class="latest-year">
<!--
(function(){var b=new Date();var c=document;c.addEventListener("DOMContentLoaded",function(){c.querySelector(".latest-year").insertAdjacentHTML("beforebegin",b.getFullYear())},false)})();
-->
</script>  Konica Minolta, Inc.</small>
<!--/row--></div>
<!--/footer__copy--></section>


<!-- Start of Konica Inc._LinkedInInsightTag -->
<script type="text/javascript">
  _bizo_data_partner_id = "7603";
</script>
<script type="text/javascript">
(function() {
  var s = document.getElementsByTagName("script")[0];
  var b = document.createElement("script");
  b.type = "text/javascript";
  b.async = true;
  b.src = (window.location.protocol === "https:" ? "https://sjs" : "http://js") + ".bizographics.com/insight.min.js";
  s.parentNode.insertBefore(b, s);
})();
</script>
<noscript>
  <img height="1" width="1" alt="" style="display:none;" src="//www.bizographics.com/collect/?pid=7603&fmt=gif" />
</noscript>
<!-- end of Konica Inc._LinkedInInsightTag -->

<!-- User Insight PCDF Code Start : konicaminolta.jp -->
<script type="text/javascript">
<!--
var _uic = _uic ||{}; var _uih = _uih ||{};_uih['id'] = 52065;
_uih['lg_id'] = '';
_uih['fb_id'] = '';
_uih['tw_id'] = '';
_uih['uigr_1'] = ''; _uih['uigr_2'] = ''; _uih['uigr_3'] = ''; _uih['uigr_4'] = ''; _uih['uigr_5'] = '';
_uih['uigr_6'] = ''; _uih['uigr_7'] = ''; _uih['uigr_8'] = ''; _uih['uigr_9'] = ''; _uih['uigr_10'] = '';

/* DO NOT ALTER BELOW THIS LINE */
/* WITH FIRST PARTY COOKIE */
(function() {
var bi = document.createElement('scri'+'pt');bi.type = 'text/javascript'; bi.async = true;
bi.src = ('https:' == document.location.protocol ? 'https://bs' : 'http://c') + '.nakanohito.jp/b3/bi.js';
var s = document.getElementsByTagName('scri'+'pt')[0];s.parentNode.insertBefore(bi, s);
})();
//-->
</script>
<!-- User Insight PCDF Code End : konicaminolta.jp -->
<script>
<!-- サイト内検索サジェスト機能用コードを挿入してください。 -->
</script>
<script src="/marsfinder/js/ext/sug.js"></script>
</footer>
