<nav class="l-header__navigation navigation-light" aria-label="サイト">
<ul>
<li><a href="/aa-bb/sample-sitename/index.html">ホーム（トップページ用テンプレート）</a></li><!--
--><li>
<dl>
<dt><a href="javascript:void(0);">第2階層下層有り（index用テンプレート）</a></dt>
<dd>
<ul>
<li><a href="/aa-bb/sample-sitename/category2nd-1/index.html">第2階層下層有り トップ</a></li><!--
--><li>
<dl>
<dt><a href="/aa-bb/sample-sitename/category2nd-1/category3rd-1/index.html">第3階層下層有り</a></dt>
<dd>
<ul>
<li><a href="/aa-bb/sample-sitename/category2nd-1/category3rd-1/category4th-1/index.html">第4階層下層有り</a></li>
<li><a href="/aa-bb/sample-sitename/category2nd-1/category3rd-1/category4th-2/index.html">第4階層下層無し</a></li>
</ul>
</dd>
</dl>
</li><!--
--><li><a href="/aa-bb/sample-sitename/category2nd-1/category3rd-2/index.html">第3階層下層無し</a></li>
</ul>
</dd>
</dl>
</li><!--
--><li><a href="/aa-bb/sample-sitename/category2nd-2/index.html">第2階層下層無し（標準ページ用テンプレート）</a></li><!--
--><li><a href="/aa-bb/sample-sitename/product.html">bizhub C759 Premium（製品情報サンプル）</a></li><!--
--><li><a href="/aa-bb/sample-sitename/header-footer-only.html">標準テンプレート以外でのサイトサンプル</a></li><!--
--><li><a href="/coding/" target="_blank">パートナー様向けポータル（外部リンクサンプル）<img src="/shared/unchangeable/img/icn_list_external_wt.png" alt="New Window"></a></li>
</ul>
</nav>