<nav class="l-header__navigation navigation-light">
<ul>
<li><a href="/aa-en/sample-sitename/index.html">Home (Top Page Sample)</a></li><!--
--><li>
<dl>
<dt><a href="javascript:void(0);">Second Level Page with Sub Pages Sample</a></dt>
<dd>
<ul>
<li><a href="/aa-en/sample-sitename/category2nd-1/index.html">Second Level Page Sample</a></li><!--
--><li>
<dl>
<dt><a href="/aa-en/sample-sitename/category2nd-1/category3rd-1/index.html">Third Level Page with Sub Pages Sample</a></dt>
<dd>
<ul>
<li><a href="/aa-en/sample-sitename/category2nd-1/category3rd-1/category4th-1/index.html">Fourth Level Page with Sub Pages Sample</a></li>
<li><a href="/aa-en/sample-sitename/category2nd-1/category3rd-1/category4th-2/index.html">Fourth Level Page Sample</a></li>
</ul>
</dd>
</dl>
</li><!--
--><li><a href="/aa-en/sample-sitename/category2nd-1/category3rd-2/index.html">Third Level Page Sample</a></li>
</ul>
</dd>
</dl>
</li><!--
--><li><a href="/aa-en/sample-sitename/category2nd-2/index.html">Second Level Page Sample</a></li><!--
--><li><a href="/aa-en/sample-sitename/product.html">Product Page Sample</a></li><!--
--><li><a href="/aa-en/sample-sitename/utility.html">CSS Utilities Sample</a></li><!--
--><li><a href="/aa-en/sample-sitename/grid.html">Grid System</a></li><!--
--><li><a href="/aa-en/sample-sitename/header-footer-only.html" target="_blank">Template for Only Header and Footer Page Sample <img src="/shared/unchangeable/img/icn_list_external_wt.png" alt="New Window"></a></li><!--
--><li><a href="dummy.link" target="_blank">External Link <img src="/shared/unchangeable/img/icn_list_external_wt.png" alt="New Window"></a></li><!--
--><li><a href="dummy.link" target="_blank">PDF Link (**KB)<img src="/shared/unchangeable/img/icn_list_pdf_wt.png" alt="PDF"></a></li>
</ul>
</nav>