<footer role="contentinfo" class="footer" id="footer">
<div class="page-top">
<p class="row">
<a href="#top"><img src="/shared/unchangeable/img/btn_page_top.png" alt="Back to top of this page"/></a>
</p>
<!--/page-top--></div>

<section class="container-fluid container-fluid-footer-menu pt-lg-30 bg-333333">
<div class="container">
<div class="row">
<div class="col-lg-10 col-lg-offset-1 col-sm-12">

<div class="row">

<dl class="col-lg-3 col-sm-12 footer-toggle-menu">
<dt class="footer-toggle-menu__ttl footer-toggle-menu__ttl--parent"><a href="#">フッタリンク親(SP時はリンクではなくトグルボタンになる)</a></dt>
<dd class="footer-toggle-menu__list">
<ul>
<li class="hidden-lg"><a href="#" class="font-weight-bold">フッタリンク親（PC時非表示/親ボタンがボタンになるので代替）</a></li>
<li><a href="#">フッタリンク子</a></li>
<li><a href="#">フッタリンク子</a></li>
<li><a href="#">フッタリンク子</a></li>
</ul>
</dd>
</dl>

<div class="col-lg-3 col-sm-12">
<ul class="footer-toggle-menu">
<li class="footer-toggle-menu__ttl"><a href="#">フッタリンク　並列</a></li>
<li class="footer-toggle-menu__ttl"><a href="#">フッタリンク　並列</a></li>
<li class="footer-toggle-menu__ttl"><a href="#">フッタリンク　並列</a></li>
<li class="footer-toggle-menu__ttl"><a href="#">フッタリンク　並列</a></li>
<li class="footer-toggle-menu__ttl"><a href="#">フッタリンク　並列</a></li>
</ul>
</div>

<dl class="col-lg-3 col-sm-12 footer-toggle-menu">
<dt class="footer-toggle-menu__ttl footer-toggle-menu__ttl--parent"><span>フッタリンク親</span></dt>
<dd class="footer-toggle-menu__list">
<ul>
<li><a href="#">子階層ページ</a></li>
<li><a href="#">子階層ページ</a></li>
<li><a href="#">子階層ページ</a></li>
<li><a href="#">子階層ページ</a></li>
<li><a href="#">子階層ページ</a></li>
</ul>
</dd>
</dl>


<dl class="col-lg-3 col-sm-12 footer-toggle-menu">
<dt class="footer-toggle-menu__ttl footer-toggle-menu__ttl--parent"><span>フッタリンク親</span></dt>
<dd class="footer-toggle-menu__list">
<ul>
<li><a href="#">子階層ページ子階層ページ子階層ページ子階層ページ子階層ページ子階層ページ子階層ページ子階層ページ</a></li>
<li><a href="#">子階層ページ</a></li>
<li><a href="#">子階層ページ</a></li>
<li><a href="#">子階層ページ</a></li>
<li><a href="#">子階層ページ</a></li>
</ul>
</dd>
</dl>

<!--/row--></div>

<!--/col--></div>

<!--/row--></div>
<!-- / .container --></div>
<!--/ .container-fluid--></section>

<section class="container-fluid container-fluid-footer-menu pt-lg-30 bg-333333">
<div class="container">
<div class="row">
<div class="col-lg-10 col-lg-offset-1 col-sm-12">

<div class="row">

<dl class="col-lg-12 col-sm-12 footer-toggle-menu">
<dt class="footer-toggle-menu__ttl footer-toggle-menu__ttl--parent"><a href="#">フッタリンク親（子はPC横並び）</a></dt>
<dd class="footer-toggle-menu__list mt-lg-10">
<ul>
<li class="hidden-lg"><a href="#" class="font-weight-bold">フッタリンク親</a></li>
<li class="d-lg-inline"><a href="#">フッタリンク子 01</a></li>
<li class="d-lg-inline"><a href="#">フッタリンク子 02</a></li>
<li class="d-lg-inline"><a href="#">フッタリンク子 03</a></li>
<li class="d-lg-inline"><a href="#">フッタリンク子 04</a></li>
<li class="d-lg-inline"><a href="#">フッタリンク子 05</a></li>
<li class="d-lg-inline"><a href="#">フッタリンク子 06</a></li>
<li class="d-lg-inline"><a href="#">フッタリンク子 07</a></li>
<li class="d-lg-inline"><a href="#">フッタリンク子 08</a></li>
<li class="d-lg-inline"><a href="#">フッタリンク子 09</a></li>
<li class="d-lg-inline"><a href="#">フッタリンク子 10</a></li>
<li class="d-lg-inline"><a href="#">フッタリンク子 11</a></li>
<li class="d-lg-inline"><a href="#">フッタリンク子 12</a></li>
<li class="d-lg-inline"><a href="#">フッタリンク子 13</a></li>
<li class="d-lg-inline"><a href="#">フッタリンク子 14</a></li>
<li class="d-lg-inline"><a href="#">フッタリンク子 15</a></li>
<li class="d-lg-inline"><a href="#">フッタリンク子 16</a></li>
<li class="d-lg-inline"><a href="#">フッタリンク子 17</a></li>
<li class="d-lg-inline"><a href="#">フッタリンク子 18</a></li>
</ul>
</dd>
</dl>

<!--/row--></div>

<!--/col--></div>

<!--/row--></div>
<!-- / .container --></div>
<!--/ .container-fluid--></section>

<section class="container-fluid container-fluid-footer-menu pt-lg-30 bg-333333">
<div class="container">
<div class="row">
<div class="col-lg-10 col-lg-offset-1 col-sm-12">

<div class="row">

<div class="col-lg-3 col-sm-12">

<div class="footer-toggle-menu">
<p class="footer-toggle-menu__ttl"><a href="#">並列フッタリンク　横置き型</a></p>
</div>

</div>

<div class="col-lg-3 col-sm-12">

<div class="footer-toggle-menu">
<p class="footer-toggle-menu__ttl"><a href="#">並列フッタリンク　横置き型</a></p>
</div>

</div>

<div class="col-lg-3 col-sm-12">

<div class="footer-toggle-menu">
<p class="footer-toggle-menu__ttl"><a href="#">並列フッタリンク　横置き型</a></p>
</div>

</div>

<div class="col-lg-3 col-sm-12">

<div class="footer-toggle-menu">
<p class="footer-toggle-menu__ttl"><a href="#">並列フッタリンク　横置き型</a></p>
</div>

</div>

<!--/row--></div>

<!--/col--></div>

<!--/row--></div>
<!-- / .container --></div>
<!--/ .container-fluid--></section>

<section class="container-fluid pt-lg-60 pb-lg-60 pb-sm-30 bg-333333 hidden-sm">
<div class="container">
<div class="row">
<div class="col-lg-8 col-lg-offset-2 col-sm-12">

<form action="" class="newsroom-pc-form bg-464646">
<div>
<label><input name="q" id="" autocomplete="off" placeholder="コニカミノルタ日本サイトを検索" type="text"></label>
<input name="ie" value="utf8" type="hidden">
<button type="submit" name="search" value="search">検索</button>
</div>
</form>

<!--/col--></div>

<!--/row--></div>
<!-- / .container --></div>
<!--/ .container-fluid--></section>
