<div class="l-header__block">
<p class="l-header__block__ttl"><a href="/aa-bb/sample-sitename/index.html">【サイト名】</a></p>
<button class="l-header__block__sm-menu-btn"><i>MENU</i><img src="/shared/unchangeable/img/btn_localmenu_close.png" alt="Close menu"></button>
<button class="l-header__block__sm-search-btn"><img src="/shared/unchangeable/img/icn_search_localnav.png" alt="Open search panel"></button>

<div class="l-header__block__textlink">
<p><a href="dummy.link">テキスト</a></p>
<!--/l-header__block__btnlink--></div>

<div class="l-header__block__btnlink btn-mail">
<p><a href="dummy.link">お問い合わせ</a></p>
<!--/l-header__block__btnlink--></div>

<div class="l-header__block__btnlink btn-form">
<p><a href="dummy.link">お問い合わせ</a></p>
<!--/l-header__block__btnlink--></div>

<div class="l-header__block__btnlink btn-login">
<p><a href="dummy.link">ログイン</a></p>
<!--/l-header__block__btnlink--></div>

<div class="l-header__block__search">
<form action="">
<label><input name="q" id="" autocomplete="off" placeholder="【サイト名】を検索" type="text"></label>
<input name="ie" value="utf8" type="hidden">
<button type="submit" name="search" value="search">検索</button>
</form>
<!-- / .l-header__block__search --></div>
<!--/l-header__block--></div>