<header role="banner" id="header" class="position-static">

<div class="row header">

<p class="header__logo"><a href="/aa-en/index.html"><img src="/shared/unchangeable/img/identity01g.svg" alt="Konica Minolta"/></a></p>

<ul class="header__function">
<li class="header__function__language"><span>EN</span>

</li><!--
--><li class="header__function__global"><a href="/selector/index.html" target="_blank"><img src="/shared/unchangeable/img/icon_header_global.png" alt="Worldwide Gateway"/></a></li>
</ul>

<!--/row header--></div>

</header>