<footer role="contentinfo" class="footer" id="footer">
<div class="page-top">
<p class="row">
<a href="#top"><img src="/shared/unchangeable/img/btn_page_top.png" alt="Back to top of this page"/></a>
</p>
<!--/page-top--></div>

<section class="container-fluid container-fluid-footer-menu pt-lg-30 bg-333333">
<div class="container">
<div class="row">
<div class="col-lg-10 col-lg-offset-1 col-sm-12">

<div class="row">

<dl class="col-lg-3 col-sm-12 footer-toggle-menu">
<dt class="footer-toggle-menu__ttl footer-toggle-menu__ttl--parent"><a href="#">Upper footer link (it chaneges into toggle in a small size screen)</a></dt>
<dd class="footer-toggle-menu__list">
<ul>
<li class="hidden-lg"><a href="#" class="font-weight-bold">Upper footer link (it is a alternative link which is visible in a small size screen)</a></li>
<li><a href="#">Lower footer link</a></li>
<li><a href="#">Lower footer link</a></li>
</ul>
</dd>
</dl>

<div class="col-lg-3 col-sm-12">
<ul class="footer-toggle-menu">
<li class="footer-toggle-menu__ttl"><a href="#">Footer link</a></li>
<li class="footer-toggle-menu__ttl"><a href="#">Footer link</a></li>
<li class="footer-toggle-menu__ttl"><a href="#">Footer link</a></li>
</ul>
</div>

<dl class="col-lg-3 col-sm-12 footer-toggle-menu">
<dt class="footer-toggle-menu__ttl footer-toggle-menu__ttl--parent"><a href="#">Upper footer link</a></dt>
<dd class="footer-toggle-menu__list">
<ul>
<li class="hidden-lg"><a href="#" class="font-weight-bold">Upper footer link</a></li>
<li><a href="#">Lower footer link</a></li>
<li><a href="#">Lower footer link</a></li>
</ul>
</dd>
</dl>


<dl class="col-lg-3 col-sm-12 footer-toggle-menu">
<dt class="footer-toggle-menu__ttl footer-toggle-menu__ttl--parent"><a href="#">Upper footer link</a></dt>
<dd class="footer-toggle-menu__list">
<ul>
<li class="hidden-lg"><a href="#" class="font-weight-bold">Upper footer link</a></li>
<li><a href="#">Lower footer link</a></li>
</ul>
</dd>
</dl>

<!--/row--></div>

<!--/col--></div>

<!--/row--></div>
<!-- / .container --></div>
<!--/ .container-fluid--></section>

<section class="container-fluid container-fluid-footer-menu pt-lg-30 bg-333333">
<div class="container">
<div class="row">
<div class="col-lg-10 col-lg-offset-1 col-sm-12">

<div class="row">

<dl class="col-lg-12 col-sm-12 footer-toggle-menu">
<dt class="footer-toggle-menu__ttl footer-toggle-menu__ttl--parent"><a href="#">Upper footer link (Lower links are arranged side by side in large size screen)</a></dt>
<dd class="footer-toggle-menu__list mt-lg-10">
<ul>
<li class="hidden-lg"><a href="#" class="font-weight-bold">Upper footer link (it is a alternative link which is visible in a small size screen)</a></li>
<li class="d-lg-inline"><a href="#">Lower link</a></li>
<li class="d-lg-inline"><a href="#">Lower link</a></li>
<li class="d-lg-inline"><a href="#">Lower link</a></li>
<li class="d-lg-inline"><a href="#">Lower link</a></li>
<li class="d-lg-inline"><a href="#">Lower link</a></li>
</ul>
</dd>
</dl>

<!--/row--></div>

<!--/col--></div>

<!--/row--></div>
<!-- / .container --></div>
<!--/ .container-fluid--></section>

<section class="container-fluid container-fluid-footer-menu pt-lg-30 bg-333333">
<div class="container">
<div class="row">
<div class="col-lg-10 col-lg-offset-1 col-sm-12">

<div class="row">

<div class="col-lg-3 col-sm-12">

<div class="footer-toggle-menu">
<p class="footer-toggle-menu__ttl"><a href="#">Footer link</a></p>
</div>

</div>

<div class="col-lg-3 col-sm-12">

<div class="footer-toggle-menu">
<p class="footer-toggle-menu__ttl"><a href="#">Footer link</a></p>
</div>

</div>

<div class="col-lg-3 col-sm-12">

<div class="footer-toggle-menu">
<p class="footer-toggle-menu__ttl"><a href="#">Footer link</a></p>
</div>

</div>

<div class="col-lg-3 col-sm-12">

<div class="footer-toggle-menu">
<p class="footer-toggle-menu__ttl"><a href="#">Footer link</a></p>
</div>

</div>

<!--/row--></div>

<!--/col--></div>

<!--/row--></div>
<!-- / .container --></div>
<!--/ .container-fluid--></section>

<section class="container-fluid pt-lg-60 pb-lg-60 pb-sm-30 bg-333333 hidden-sm">
<div class="container">
<div class="row">
<div class="col-lg-8 col-lg-offset-2 col-sm-12">

<form action="" class="newsroom-pc-form bg-464646">
<div>
<label><input name="q" id="" autocomplete="off" placeholder="Type here to search" type="text"></label>
<input name="ie" value="utf8" type="hidden">
<button type="submit" name="search" value="search">Search</button>
</div>
</form>
<!--/col--></div>

<!--/row--></div>
<!-- / .container --></div>
<!--/ .container-fluid--></section>
