<section class="footer__copy" id="dynamic-select">
<div class="row">
<ul>
<li><a href="/siteinfo/index.html">Terms of Use</a></li>
</ul>
<small>©2011-<script class="latest-year">
<!--
(function(){var b=new Date();var c=document;c.addEventListener("DOMContentLoaded",function(){c.querySelector(".latest-year").insertAdjacentHTML("beforebegin",b.getFullYear())},false)})();
-->
</script>  Konica Minolta, Inc.</small>
<!--/row--></div>
<!--/footer__copy--></section>
</footer>
