<header role="banner" id="header" class="position-static">

<div class="row header">

<p class="header__logo"><a href="/aa-bb/index.html"><img src="/shared/unchangeable/img/identity01g.svg" alt="Konica Minolta"/></a></p>

<nav class="header__nav" aria-label="メイン">
<ul>
<li class="product"><a href="#" class="sp-slide-toggle">製品・サービス</a>
<div class="second-wrap">
<div class="row">
<ul class="gnavi-2nd-block">
<li><a href="https://www.konicaminolta.jp/business/index.html" aria-haspopup="true" target="_blank">ビジネスソリューション</a>
<div class="third-wrap">

<div class="gnavi-3rd-block">

<div class="gnavi-3rd-block__left">
<p class="gnavi-3rd-block__left__ttl"><a href="https://www.konicaminolta.jp/business/index.html" target="_blank">ビジネスソリューション</a></p>
<p class="gnavi-3rd-block__left__txt">複合機（MFP）／レーザープリンター／ファイリング機器／ソフトウェア・周辺機器／クラウドサービス／出力環境最適化サービス</p>

<dl class="gnavi-3rd-block__left__list">
<dt>Index</dt>
<dd><a href="https://www.konicaminolta.jp/business/solution/index.html" target="_blank">ソリューション</a></dd>
<dd><a href="https://www.konicaminolta.jp/business/service/index.html" target="_blank">サービス</a></dd>
<dd><a href="https://www.konicaminolta.jp/business/products/index.html" target="_blank">製品情報</a></dd>
<dd><a href="https://www.konicaminolta.jp/business/user_case/index.html" target="_blank">導入事例</a></dd>
</dl>
<dl class="gnavi-3rd-block__left__list">
<dt>主要製品・サービス</dt>
<dd><a href="https://www.konicaminolta.jp/business/products/copiers/index.html" target="_blank">複合機／複写機</a></dd>
<dd><a href="https://www.konicaminolta.jp/business/products/printers/index.html" target="_blank">プリンター</a></dd>
<dd><a href="https://www.konicaminolta.jp/business/products/software/index.html" target="_blank">ソフトウェア</a></dd>
<dd><a href="https://www.konicaminolta.jp/business/solution/innovation/document_work/digital_workflow/index.html" target="_blank">デジタルワークフローソリューション</a></dd>
</dl>

<!--/gnavi-3rd-block__left--></div>

<div class="gnavi-3rd-block__right">
<p class="gnavi-3rd-block__right__img"><img src="/shared/unchangeable/img/bg_gnavi_3rd_002.jpg" alt=""></p>
<!--/gnavi-3rd-block__right--></div>

<div class="gnavi-3rd-block__utility">
<ul>
<li><a href="https://www.konicaminolta.jp/business/support/contact.html" class="btn btn-contact" target="_blank"><i>お問い合わせ</i></a></li><!--
--><li><a href="https://www.konicaminolta.jp/business/support/index.html" class="btn btn-support" target="_blank"><i>サポート</i></a></li><!--
--><li><a href="https://www.konicaminolta.jp/business/download/index.html" class="btn btn-download" target="_blank"><i>ダウンロード</i></a></li>
</ul>
</div>

<!--/gnavi-3rd-block--></div>
<!--/third-wrap--></div>
</li>
<li><a href="https://www.konicaminolta.jp/business/products/graphic/index.html" target="_blank">プロダクションプリント &amp; グラフィック</a>
<div class="third-wrap">
<div class="gnavi-3rd-block">

<div class="gnavi-3rd-block__left">
<p class="gnavi-3rd-block__left__ttl"><a href="https://www.konicaminolta.jp/business/products/graphic/index.html" target="_blank">プロダクションプリント &amp; グラフィック</a></p>
<p class="gnavi-3rd-block__left__txt">デジタルカラー印刷システム／デジタルモノクロ印刷システム／デジタル色校正システム／CTP（印刷用プレート）／プリプレス生産システム</p>

<dl class="gnavi-3rd-block__left__list">
<dt>Index</dt>
<dd><a href="https://www.konicaminolta.jp/business/solution/index.html" target="_blank">ソリューション</a></dd>
<dd><a href="https://www.konicaminolta.jp/business/service/index.html" target="_blank">サービス</a></dd>
<dd><a href="https://www.konicaminolta.jp/business/products/index.html" target="_blank">製品情報</a></dd>
<dd><a href="https://www.konicaminolta.jp/business/user_case/index.html" target="_blank">導入事例</a></dd>
</dl>
<dl class="gnavi-3rd-block__left__list">
<dt>主要製品・サービス</dt>
<dd><a href="https://www.konicaminolta.jp/business/products/graphic/printing_process.html" target="_blank">製品別ポジショニングマップ</a></dd>
<dd><a href="https://www.konicaminolta.jp/business/products/graphic/ondemand_print/index.html" target="_blank">デジタル印刷システム</a></dd>
<dd><a href="https://www.konicaminolta.jp/business/products/graphic/mgi/index.html" target="_blank">フランスMGI社製品</a></dd>
<dd><a href="https://www.konicaminolta.jp/business/products/graphic/label_print/index.html" target="_blank">ラベルプリンター</a></dd>
</dl>

<!--/gnavi-3rd-block__left--></div>

<div class="gnavi-3rd-block__right">
<p class="gnavi-3rd-block__right__img"><img src="/shared/unchangeable/img/bg_gnavi_3rd_003.jpg" alt=""></p>
<!--/gnavi-3rd-block__right--></div>



<div class="gnavi-3rd-block__utility">
<ul>
<li><a href="https://www.konicaminolta.jp/business/support/graphic/contact/index.html" class="btn btn-contact" target="_blank"><i>お問い合わせ
</i></a></li><!--
--><li><a href="https://www.konicaminolta.jp/business/support/index.html" class="btn btn-support" target="_blank"><i>サポート</i></a></li><!--
--><li><a href="https://www.konicaminolta.jp/business/download/index.html" class="btn btn-download" target="_blank"><i>ダウンロード</i></a></li>
</ul>
</div>

<!--/gnavi-3rd-block--></div>
<!--/third-wrap--></div>
</li>
<li><a href="https://www.konicaminolta.jp/inkjet/index.html" target="_blank">産業用インクジェット</a>
<div class="third-wrap">
<div class="gnavi-3rd-block">

<div class="gnavi-3rd-block__left">
<p class="gnavi-3rd-block__left__ttl"><a href="https://www.konicaminolta.jp/inkjet/index.html" target="_blank">産業用インクジェット</a></p>
<p class="gnavi-3rd-block__left__txt">インクジェットヘッド／インクジェットテキスタイルプリンター／インクジェットインク</p>
<dl class="gnavi-3rd-block__left__list">
<dt>Index</dt>
<dd><a href="https://www.konicaminolta.jp/inkjet/products/index.html" target="_blank">製品情報</a></dd>
<dd><a href="https://www.konicaminolta.jp/inkjet/support/index.html" target="_blank">サポート</a></dd>
<dd><a href="https://www.konicaminolta.jp/inkjet/technology/index.html" target="_blank">インクジェット技術情報</a></dd>
<dd><a href="https://www.konicaminolta.jp/inkjet/event/index.html" target="_blank">イベント情報</a></dd>
</dl>
<dl class="gnavi-3rd-block__left__list">
<dt>クイックリンク</dt>
<dd><a href="https://www.konicaminolta.jp/inkjet/technology/technology.html" target="_blank">インクジェット技術概要</a></dd>
<dd><a href="https://www.konicaminolta.jp/inkjet/technology/term.html" target="_blank">インクジェット用語</a></dd>
</dl>
<!--/gnavi-3rd-block__left--></div>

<div class="gnavi-3rd-block__right">
<p class="gnavi-3rd-block__right__img"><img src="/shared/unchangeable/img/bg_gnavi_3rd_004.jpg" alt=""></p>
<!--/gnavi-3rd-block__right--></div>


<div class="gnavi-3rd-block__utility">
<ul>
<li><a href="https://www.konicaminolta.jp/inkjet/support/index.html" class="btn btn-support" target="_blank"><i>サポート</i></a></li><!--
--><li><a href="https://www.konicaminolta.jp/inkjet/support/catalog_download/textile_printers/index.html" class="btn btn-download" target="_blank"><i>ダウンロード</i></a></li>
</ul>
</div>

<!--/gnavi-3rd-block--></div>
<!--/third-wrap--></div>
</li>
<li><a href="https://www.konicaminolta.jp/healthcare/index.html" target="_blank">ヘルスケア</a>

<div class="third-wrap">
<div class="gnavi-3rd-block">

<div class="gnavi-3rd-block__left">
<p class="gnavi-3rd-block__left__ttl"><a href="https://www.konicaminolta.jp/healthcare/index.html" target="_blank">ヘルスケア</a></p>
<p class="gnavi-3rd-block__left__txt">デジタルX線画像診断システム／デジタルマンモグラフィー／超音波画像診断装置／医療用画像情報システム／パルスオキシメーター／黄疸計／医療ICTサービス／造影剤</p>
<dl class="gnavi-3rd-block__left__list">
<dt>Index</dt>
<dd><a href="https://www.konicaminolta.jp/healthcare/products/index.html" target="_blank">製品情報</a></dd>
<dd><a href="https://www.konicaminolta.jp/healthcare/seminar/index.html" target="_blank">学会・セミナー・展示会</a></dd>
<dt>グループ会社</dt>
<dd><a href="https://www.konicaminolta.jp/medical-solutions/" target="_blank">コニカミノルタメディカルソリューションズ</a></dd>
</dl>
<dl class="gnavi-3rd-block__left__list">
<dt>クイックリンク</dt>
<dd><a href="https://www.konicaminolta.jp/healthcare/products/dr/index.html" target="_blank">DR（デジタルラジオグラフィー）</a></dd>
<dd><a href="https://www.konicaminolta.jp/healthcare/products/cr/index.html" target="_blank">CR（コンピューテッドラジオグラフィー）</a></dd>
<dd><a href="https://www.konicaminolta.jp/healthcare/products/us/index.html" target="_blank">US（超音波診断装置）</a></dd>
<dd><a href="https://www.konicaminolta.jp/healthcare/products/imaging/index.html" target="_blank">医用画像情報システム</a></dd>
<dd><a href="https://www.konicaminolta.jp/healthcare/infomity/index.html" target="_blank">infomity</a></dd>
</dl>
<!--/gnavi-3rd-block__left--></div>


<div class="gnavi-3rd-block__right">
<p class="gnavi-3rd-block__right__img"><img src="/shared/unchangeable/img/bg_gnavi_3rd_005.jpg" alt=""></p>
<!--/gnavi-3rd-block__right--></div>



<div class="gnavi-3rd-block__utility">
<ul>
<li><a href="https://ank2.konicaminolta.net/form/pub/healthcare/catalog_req?_ga=1.29318900.919447588.1379138942" class="btn btn-contact" target="_blank"><i>カタログ請求</i></a></li><!--
--><li><a href="https://www.konicaminolta.jp/healthcare/support/index.html" class="btn btn-download" target="_blank"><i>サポート・お問い合わせ</i></a></li>
</ul>
</div>

<!--/gnavi-3rd-block--></div>
<!--/third-wrap--></div>

</li>
<li><a href="https://www.konicaminolta.jp/instruments/index.html" target="_blank">計測機器</a>
<div class="third-wrap">
<div class="gnavi-3rd-block">

<div class="gnavi-3rd-block__left">

<p class="gnavi-3rd-block__left__ttl"><a href="https://www.konicaminolta.jp/instruments/index.html" target="_blank">計測機器</a></p>
<p class="gnavi-3rd-block__left__txt">測色計／照度計／輝度計／基準太陽電池セル</p>
<dl class="gnavi-3rd-block__left__list">
<dt>Index</dt>
<dd><a href="https://www.konicaminolta.jp/instruments/products/index.html" target="_blank">製品情報</a></dd>
<dd><a href="https://www.konicaminolta.jp/instruments/industry/index.html" target="_blank">活用シーン</a></dd>
<dd><a href="https://www.konicaminolta.jp/instruments/event/index.html" target="_blank">セミナー・展示会情報</a></dd>
</dl>
<dl class="gnavi-3rd-block__left__list">
<dt>クイックリンク</dt>
<dd><a href="https://www.konicaminolta.jp/instruments/web_magazine/index.html" target="_blank">Webマガジン ハカル力</a></dd>
<dd><a href="https://www.konicaminolta.jp/instruments/knowledge/color/index.html" target="_blank">色色雑学</a></dd>
<dd><a href="https://www.konicaminolta.jp/instruments/knowledge/light_bulb/index.html" target="_blank">ひかり豆辞典</a></dd>
<dd><a href="https://www.konicaminolta.jp/instruments/knowledge/fluorescence_point/index.html" target="_blank">濃度計のツボ</a></dd>
<dd><a href="https://www.konicaminolta.jp/instruments/concept/index.html" target="_blank">The Standard in Measuring Color & Light</a></dd>
</dl>
<!--/gnavi-3rd-block__left--></div>


<div class="gnavi-3rd-block__right">
<p class="gnavi-3rd-block__right__img"><img src="/shared/unchangeable/img/bg_gnavi_3rd_006.jpg" alt=""></p>
<!--/gnavi-3rd-block__right--></div>


<div class="gnavi-3rd-block__utility">
<ul>
<li><a href="https://wwws.konicaminolta.jp/instruments/member/about_use/" class="btn" target="_blank"><i>Web会員登録</i></a></li><!--
--><li><a href="https://www.konicaminolta.jp/instruments/support/index.html" class="btn" target="_blank"><i>お客様サポート</i></a></li><!--
--><li><a href="https://www.konicaminolta.jp/instruments/support/repair_proof/index.html" class="btn" target="_blank"><i>修理・校正</i></a></li>
</ul>
</div>

<!--/gnavi-3rd-block--></div>
<!--/third-wrap--></div>
</li>
<li><a href="https://www.konicaminolta.jp/opt/index.html" target="_blank">光学製品</a>
<div class="third-wrap">
<div class="gnavi-3rd-block">

<div class="gnavi-3rd-block__left">
<p class="gnavi-3rd-block__left__ttl"><a href="https://www.konicaminolta.jp/opt/index.html" target="_blank">光学製品</a></p>
<p class="gnavi-3rd-block__left__txt">レンズユニット／光ディスク用ピックアップレンズ</p>
<dl class="gnavi-3rd-block__left__list">
<dt>Index</dt>
<dd><a href="https://www.konicaminolta.jp/opt/products/index.html" target="_blank">製品情報</a></dd>
<dd><a href="https://www.konicaminolta.jp/opt/about/index.html" target="_blank">事業情報</a></dd>
</dl>
<dl class="gnavi-3rd-block__left__list">
<dt>クイックリンク</dt>
<dd><a href="https://www.konicaminolta.jp/opt/about/index.html" target="_blank">技術概要</a></dd>
<dd><a href="https://www.konicaminolta.jp/opt/about/dvd.html" target="_blank">光ディスク用対物レンズ</a></dd>
<dd><a href="https://www.konicaminolta.jp/opt/about/intellectual_property/index.html" target="_blank">知的財産方針</a></dd>
<dt>ご案内</dt>
<dd><a href="http://ca.konicaminolta.jp/index.html" target="_blank">カメラ関連製品・双眼鏡・フィルムスキャナー製品などに関するお問い合わせ先</a></dd>
</dl>

<!--/gnavi-3rd-block__left--></div>


<div class="gnavi-3rd-block__right">
<p class="gnavi-3rd-block__right__img"><img src="/shared/unchangeable/img/bg_gnavi_3rd_007.jpg" alt=""></p>
<!--/gnavi-3rd-block__right--></div>


<div class="gnavi-3rd-block__utility">
<ul>
<li><a href="https://www.konicaminolta.jp/opt/support/index.html" class="btn" target="_blank"><i>お問い合わせ・サポート</i></a></li>
</ul>
</div>

<!--/gnavi-3rd-block--></div>
<!--/third-wrap--></div>
</li>
<li><a href="https://www.konicaminolta.jp/oled/index.html" target="_blank">有機EL照明</a>

<div class="third-wrap">
<div class="gnavi-3rd-block">

<div class="gnavi-3rd-block__left">
<p class="gnavi-3rd-block__left__ttl"><a href="https://www.konicaminolta.jp/oled/index.html" target="_blank">有機EL照明</a></p>
<dl class="gnavi-3rd-block__left__list">
<dt>Index</dt>
<dd><a href="https://www.konicaminolta.jp/oled/index.html" target="_blank">有機EL照明 Top</a></dd>
<!--
<dd><a href="https://www.konicaminolta.jp/oled/research/index.html" target="_blank">有機EL照明とは</a></dd>
<dd><a href="https://www.konicaminolta.jp/oled/value/index.html" target="_blank">有機EL照明の真髄</a></dd>
<dd><a href="https://www.konicaminolta.jp/oled/products/index.html" target="_blank">製品情報</a></dd>
<dd><a href="https://www.konicaminolta.jp/oled/oledlabo/index.html" target="_blank">OLEDラボ</a></dd>
<dd><a href="https://www.konicaminolta.jp/oled/user_case/index.html" target="_blank">採用事例</a></dd>
<dd><a href="https://www.konicaminolta.jp/oled/faq/index.html" target="_blank">Q&amp;A</a></dd>
<dd><a href="https://www.konicaminolta.jp/oled/about/index.html" target="_blank">事業紹介</a></dd>-->
</dl>
<!--
<dl class="gnavi-3rd-block__left__list">
<dt>クイックリンク</dt>
<dd><a href="https://www.konicaminolta.jp/oled/products/index.html" target="_blank">フレキシブル有機EL照明</a></dd>
</dl>-->

<!--/gnavi-3rd-block__left--></div>


<div class="gnavi-3rd-block__right">
<p class="gnavi-3rd-block__right__img"><img src="/shared/unchangeable/img/bg_gnavi_3rd_008.jpg" alt=""></p>
<!--/gnavi-3rd-block__right--></div>

<!--
<div class="gnavi-3rd-block__utility">
<ul>
<li><a href="https://ank2.konicaminolta.net/form/pub/oled/contact" class="btn" target="_blank"><i>お問い合わせ</i></a></li>
</ul>
</div>-->

<!--/gnavi-3rd-block--></div>
<!--/third-wrap--></div>

</li>
<li><a href="https://www.konicaminolta.jp/al/index.html" target="_blank">機能材料</a>
<div class="third-wrap">
<div class="gnavi-3rd-block">

<div class="gnavi-3rd-block__left">
<p class="gnavi-3rd-block__left__ttl"><a href="https://www.konicaminolta.jp/al/index.html" target="_blank">機能材料</a></p>
<p class="gnavi-3rd-block__left__txt">液晶偏光板用TACフィルム／ガラス乾板／バリアフィルム／機能性ウィンドウフィルム</p>
<dl class="gnavi-3rd-block__left__list">
<dt>製品情報</dt>
<dd><a href="https://www.konicaminolta.jp/al/products/tac_film/" target="_blank">液晶偏光板用TACフィルム</a></dd>
<dd><a href="https://www.konicaminolta.jp/al/products/barrier_film/index.html" target="_blank">バリアフィルム</a></dd>
<dd><a href="https://www.konicaminolta.jp/al/products/window_film/" target="_blank">機能性ウィンドウフィルム</a></dd>
<dd><a href="https://www.konicaminolta.jp/al/products/resolution/" target="_blank">ガラス乾板</a></dd>
</dl>
<dl class="gnavi-3rd-block__left__list">
<dt>クイックリンク</dt>
<dd><a href="https://www.konicaminolta.jp/about/corporate/group/pcl/index.html" target="_blank">コニカミノルタケミカル株式会社</a></dd>
</dl>

<!--/gnavi-3rd-block__left--></div>


<div class="gnavi-3rd-block__right">
<p class="gnavi-3rd-block__right__img"><img src="/shared/unchangeable/img/bg_gnavi_3rd_009.jpg" alt=""></p>
<!--/gnavi-3rd-block__right--></div>


<div class="gnavi-3rd-block__utility">
<ul>
<li><a href="https://www.konicaminolta.jp/al/support/index.html" class="btn" target="_blank"><i>お問い合わせ・サポート</i></a></li>
</ul>
</div>

<!--/gnavi-3rd-block--></div>
<!--/third-wrap--></div>
</li>
<li><a href="https://www.konicaminolta.jp/planetarium/index.html" target="_blank">プラネタリウム / VRサービス</a>
<div class="third-wrap">
<div class="gnavi-3rd-block">

<div class="gnavi-3rd-block__left">
<p class="gnavi-3rd-block__left__ttl"><a href="https://www.konicaminolta.jp/planetarium/index.html" target="_blank">プラネタリウム / VRサービス</a></p>
<p class="gnavi-3rd-block__left__txt">光学式プラネタリウム／全天周デジタル映像投映システム／ドーム映像コンテンツ／プラネタリウム施設の経営・運営</p>
<dl class="gnavi-3rd-block__left__list">
<dt>プラネタリウム事業</dt>
<dd><a href="https://www.konicaminolta.jp/planetarium/hard/index.html" target="_blank">ハード情報</a></dd>
<dd><a href="https://www.konicaminolta.jp/planetarium/program/index.html" target="_blank">コンテンツ情報</a></dd>
<dd><a href="https://www.konicaminolta.jp/planetarium/management/index.html" target="_blank">直営館の運営</a></dd>
<dd><a href="https://www.konicaminolta.jp/planetarium/institution/index.html" target="_blank">設置館情報</a></dd>
</dl>
<dl class="gnavi-3rd-block__left__list">
<dt>プラネタリウム施設情報</dt>
<dd><a href="https://planetarium.konicaminolta.jp/manten/" target="_blank">“満天”in Sunshine City</a></dd>
<dd><a href="https://planetarium.konicaminolta.jp/tenku/" target="_blank">“天空”in 東京スカイツリータウン&reg;</a></dd>
<dd><a href="https://planetarium.konicaminolta.jp/stariumnavi/" target="_blank">スタリウムNavi</a></dd>
</dl>
<dl class="gnavi-3rd-block__left__list">
<dt>VRサービス</dt>
<dd><a href="https://planetarium.konicaminolta.jp/VirtuaLink/" target="_blank">VirtuaLink</a></dd>
</dl>
<!--/gnavi-3rd-block__left--></div>


<div class="gnavi-3rd-block__right">
<p class="gnavi-3rd-block__right__img"><img src="/shared/unchangeable/img/bg_gnavi_3rd_010.jpg" alt=""></p>
<!--/gnavi-3rd-block__right--></div>



<div class="gnavi-3rd-block__utility">
<ul>
<li><a href="https://www.konicaminolta.jp/planetarium/support/index.html" class="btn" target="_blank"><i>お問い合わせ</i></a></li>
</ul>
</div>

<!--/gnavi-3rd-block--></div>
<!--/third-wrap--></div>
</li>

<li class="see-more"><a href="#">See More</a>
<div class="third-wrap">
<div class="gnavi-3rd-block">

<div class="gnavi-3rd-block__left">
<ul class="gnavi-3rd-block__left__list mt-lg-0">
<li class="mt-lg-0"><a href="https://www.konicaminolta.jp/ailingual/" target="_blank">20カ国語マニュアル作成・共有ソリューション AiLingual</a></li>
<li><a href="https://www.konicaminolta.jp/melon/" target="_blank">医療機関向けコミュニケーション支援サービス MELON</a></li>
<li><a href="https://infohello.konicaminolta.jp/" target="_blank">オンライン英会話</a></li>
<li><a href="https://kunkunbody.konicaminolta.jp/" target="_blank">Kunkun body（クンクン ボディ）</a></li>
<li><a href="https://www.konicaminolta.jp/business/solution/innovation/expertise/care_support/index.html" target="_blank">ケアサポートソリューション</a></li>
<li><a href="https://www.konicaminolta.jp/about/research/future/wcc/index.html" target="_blank">ウェアラブルコミュニケーター</a></li>
<li><a href="https://www.konicaminolta.jp/about/research/future/3dlr/index.html" target="_blank">3Dレーザーレーダー</a></li>
<li><a href="https://www.konicaminolta.jp/about/research/future/hstt/index.html" target="_blank">蛍光ナノイメージング</a></li>
</ul>
<dl class="gnavi-3rd-block__left__list mt-lg-0">
<dt class="mt-lg-0">グループ会社</dt>
<dd><a href="http://www.kinkos.co.jp/" target="_blank">キンコーズ・ジャパン</a></dd>
<dd><a href="https://www.konicaminolta.jp/ms/" target="_blank">コニカミノルタマーケティングサービス</a></dd>
<!--<dd><a href="https://www.kompo.jp/" target="_blank">コニカミノルタ パイオニア OLED 株式会社</a></dd>-->
<dt>ご案内</dt>
<dd><a href="http://ca.konicaminolta.jp/index.html" target="_blank">カメラ関連製品・双眼鏡・フィルムスキャナー製品などに関するお問い合わせ先</a></dd>
</dl>
<!--/gnavi-3rd-block__left--></div>

<div class="gnavi-3rd-block__right">
<p class="gnavi-3rd-block__right__img"><img src="/shared/unchangeable/img/bg_gnavi_3rd_011.jpg" alt=""></p>
<!--/gnavi-3rd-block__right--></div>

<!--/gnavi-3rd-block--></div>
<!--/third-wrap--></div>
</li>

</ul>

<ul class="gnavi-2nd-block-all">
<li><a href="/aa-bb/products_service/viewall.html">製品サービス一覧ページ</a></li>
</ul>

<!--/row--></div>
<p class="close-second-wrap"><span>Close</span></p>
<!--/second-wrap--></div>

</li>
<li class="about"><a href="#" class="sp-slide-toggle">企業情報</a>

<div class="second-wrap">
<div class="row">
<p class="h2"><a href="/aa-bb/corporate/index.html">企業情報</a></p>

<div class="row">
<dl class="col-lg-4 gnavi-2nd-block">
<dt>企業情報</dt>
<dd><a href="/aa-bb/corporate/index.html">HOME</a></dd>
<dd><a href="/aa-bb/corporate/glance.html">基本情報</a></dd>
<dd><a href="/aa-bb/corporate/outline.html">会社概要</a></dd>
<dd><a href="/aa-bb/corporate/domain.html">事業領域</a></dd>
<dd><a href="/aa-bb/corporate/site.html">拠点一覧</a></dd>
<dd><a href="https://www.konicaminolta.jp/about/release/index.html" target="_blank">ニュースリリース</a></dd>
<dd><a href="https://video.konicaminolta.com/" target="_blank">動画ライブラリー</a></dd>
<dt>研究開発</dt>
<dd><a href="https://www.konicaminolta.jp/about/research/index.html" target="_blank">HOME</a></dd>
<dd><a href="https://www.konicaminolta.jp/about/research/future/index.html" target="_blank">Technologies for the Future</a></dd>
</dl>

<dl class="col-lg-4 gnavi-2nd-block">
<dt>株主・投資家情報</dt>
<dd><a href="https://www.konicaminolta.jp/about/investors/index.html" target="_blank">HOME</a></dd>
<dd><a href="https://www.konicaminolta.jp/about/investors/management/index.html" target="_blank">経営方針</a></dd>
<dd><a href="https://www.konicaminolta.jp/about/investors/ir_library/index.html" target="_blank">IR資料室</a></dd>
<dd><a href="https://www.konicaminolta.jp/about/investors/individual/index.html" target="_blank">個人投資家の皆様へ</a></dd>
<dt>CSR（社会・環境活動） </dt>
<dd><a href="https://www.konicaminolta.jp/about/csr/index.html" target="_blank">HOME</a></dd>
<dd><a href="https://www.konicaminolta.jp/about/csr/csr/message/index.html" target="_blank">トップコミットメント</a></dd>
<dd><a href="https://www.konicaminolta.jp/about/csr/csr/vision/index.html" target="_blank">コニカミノルタのCSR</a></dd>
</dl>

<dl class="col-lg-4 gnavi-2nd-block">
<dt>採用情報</dt>
<dd><a href="https://www.konicaminolta.jp/about/recruit/index.html" target="_blank">HOME</a></dd>
<dd><a href="https://www.konicaminolta.jp/about/recruit/stu/index.html" target="_blank">新卒採用情報</a></dd>
<dd><a href="https://www.konicaminolta.jp/about/recruit/car/index.html" target="_blank">キャリア採用情報</a></dd>
<dt>コニカミノルタの取り組み</dt>
<dd><a href="https://www.konicaminolta.jp/athlete/index.html" target="_blank">陸上競技部</a></dd>
<dd><a href="https://www.konicaminolta.jp/runpro/index.html" target="_blank">ランニングプロジェクト</a></dd>
<dd><a href="https://www.konicaminolta.jp/com_message/index.html" target="_blank">Giving Shape to Ideas SHOWCASE</a></dd>
</dl>

<!--/row--></div>

<!--/row--></div>
<p class="close-second-wrap"><span>Close</span></p>
<!--/2nd-wrap--></div></li>


<li class="support"><a href="/aa-bb/support/index.html">サポート・ダウンロード</a></li>
<li class="contact"><a href="/aa-bb/contact/index.html">お問い合わせ</a></li>
</ul>
<p class="header__nav__close"><span>close</span></p>
</nav>

<ul class="header__function">
<li class="header__function__language"><span>JP</span>

</li><!--
--><li class="header__function__global"><a href="/selector/index.html" target="_blank"><img src="/shared/unchangeable/img/icon_header_global.png" alt="Worldwide Gateway"/></a></li><!--
--><li class="header__function__menu"><button><img src="/shared/unchangeable/img/btn_sp_menu.png" alt="Open menu"/></button></li>
</ul>

<!--/row header--></div>

</header>